from pylab import *

pixa = loadtxt('t=0.dat', 'float')
img = imshow(pixa, aspect='equal', extent=(0,300,0,300))
img.set_cmap('gray')
colorbar()
xlabel(r'$x \, (m)$')
ylabel(r'$y \, (m)$')
savefig("plot1.png")

plt.figure()
pixa = loadtxt('t=0.1.dat', 'float')
img = imshow(pixa, aspect='equal', extent=(0,300,0,300))
img.set_cmap('gray')
colorbar()
xlabel(r'$x \, (m)$')
ylabel(r'$y \, (m)$')
savefig("plot2.png")

plt.figure()
pixa = loadtxt('t=0.2.dat', 'float')
img = imshow(pixa, aspect='equal', extent=(0,300,0,300))
img.set_cmap('gray')
colorbar()
xlabel(r'$x \, (m)$')
ylabel(r'$y \, (m)$')
savefig("plot3.png")

plt.figure()
pixa = loadtxt('t=0.4.dat', 'float')
img = imshow(pixa, aspect='equal', extent=(0,300,0,300))
img.set_cmap('gray')
colorbar()
xlabel(r'$x \, (m)$')
ylabel(r'$y \, (m)$')
savefig("plot4.png")
